version: "3.5"
services:
  centos7apcu:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  centos7apcurel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.rel

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
