version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  apcubuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7apcu
          build_service: centos7apcu
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos7apcurel
          build_service: centos7apcurel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcu
          build_service: centos8apcu
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos8apcurel
          build_service: centos8apcurel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7apcuphp73
          build_file: docker-compose.php73.yml
          build_service: centos7apcuphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcuphp73
          build_file: docker-compose.php73.yml
          build_service: centos8apcuphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7apcuphp74
          build_file: docker-compose.php74.yml
          build_service: centos7apcuphp74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8apcuphp74
          build_file: docker-compose.php74.yml
          build_service: centos8apcuphp74
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7apcuphp7build
          compose_file: build/php71/docker-compose.yml
          build_service: centos7apcuphp7build
          requires:
            - centos7apcu
      - docker-rpmbuild/image:
          name: centos7apcuphp7buildrel
          compose_file: build/php71/docker-compose.yml
          build_service: centos7apcuphp7buildrel
          requires:
            - centos7apcurel
      - docker-rpmbuild/image:
          name: centos8apcuphp7build
          compose_file: build/php71/docker-compose.yml
          build_service: centos8apcuphp7build
          requires:
            - centos8apcu
      - docker-rpmbuild/image:
          name: centos8apcuphp7buildrel
          compose_file: build/php71/docker-compose.yml
          build_service: centos8apcuphp7buildrel
          requires:
            - centos8apcurel
      - docker-rpmbuild/image:
          name: centos7apcuphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos7apcuphp73build
          requires:
            - centos7apcuphp73
      - docker-rpmbuild/image:
          name: centos8apcuphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos8apcuphp73build
          requires:
            - centos8apcuphp73
      - docker-rpmbuild/image:
          name: centos7apcuphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos7apcuphp74build
          requires:
            - centos7apcuphp74
      - docker-rpmbuild/image:
          name: centos8apcuphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos8apcuphp74build
          requires:
            - centos8apcuphp74

